import * as fs from 'fs';
import * as path from 'path';
import { DiscoveredElement } from '../core/PageCrawler';

/**
 * PropertiesWriter
 * ----------------
 * Writes NEW elements to a .properties file.
 * Rules:
 *   - If {Page}.properties exists → APPEND new elements only (never overwrite)
 *   - If {Page}.properties does not exist → create new file
 *   - Existing entries are NEVER touched
 *   - Elements marked source: existing are SKIPPED (already in registry)
 */
export class PropertiesWriter {
  private propertiesDir: string;

  constructor() {
    this.propertiesDir = path.resolve(process.cwd(), 'src', 'pages', 'properties');
  }

  /**
   * Writes new elements to {Page}.properties.
   * Returns the path to the properties file.
   *
   * @param pageName - Page name (e.g. "Support") → maps to Support.properties
   * @param elements - All elements from plan (new + existing mixed)
   */
  write(
    pageName: string,
    elements: (DiscoveredElement & { source?: string; ref?: string })[]
  ): string {
    const filePath = path.join(this.propertiesDir, `${pageName}.properties`);

    // Filter to new elements only
    const newElements = elements.filter((e) => e.source !== 'existing');

    if (newElements.length === 0) {
      console.log(`[PropertiesWriter] No new elements for ${pageName} — all already exist in registry.`);
      return filePath;
    }

    if (fs.existsSync(filePath)) {
      this._append(filePath, pageName, newElements);
    } else {
      this._create(filePath, pageName, newElements);
    }

    return filePath;
  }

  // ─── Private ──────────────────────────────────────────────────────────────

  private _create(
    filePath: string,
    pageName: string,
    elements: (DiscoveredElement & { source?: string })[]
  ): void {
    const lines: string[] = [];
    lines.push(`# ${pageName} - Elements`);
    lines.push(`# Generated by Generator Agent — ${new Date().toLocaleDateString()}`);
    lines.push(`# TODO: Verify locators against live DOM before using in tests`);
    lines.push('');

    // Group by element type
    const groups = this._groupByType(elements);

    for (const [groupName, groupElements] of Object.entries(groups)) {
      if (groupElements.length === 0) continue;
      lines.push(`# ${pageName} - ${groupName}`);
      groupElements.forEach((el) => {
        lines.push(`${el.key}=${el.locator}`);
      });
      lines.push('');
    }

    fs.writeFileSync(filePath, lines.join('\n'), 'utf-8');
    console.log(`[PropertiesWriter] Created: ${filePath} (${elements.length} elements)`);
  }

  private _append(
    filePath: string,
    pageName: string,
    elements: (DiscoveredElement & { source?: string })[]
  ): void {
    // Read existing file to check for duplicate keys
    const existing = fs.readFileSync(filePath, 'utf-8');
    const existingKeys = new Set(
      existing.split('\n')
        .filter((l) => l.includes('=') && !l.startsWith('#'))
        .map((l) => l.split('=')[0].trim())
    );

    // Only append keys that don't already exist
    const toAppend = elements.filter((e) => !existingKeys.has(e.key));

    if (toAppend.length === 0) {
      console.log(`[PropertiesWriter] No new keys to append to ${pageName}.properties — all keys already present.`);
      return;
    }

    const lines: string[] = [''];
    lines.push(`# ${pageName} - New Elements (appended by Generator Agent — ${new Date().toLocaleDateString()})`);
    toAppend.forEach((el) => {
      lines.push(`${el.key}=${el.locator}`);
    });
    lines.push('');

    fs.appendFileSync(filePath, lines.join('\n'), 'utf-8');
    console.log(`[PropertiesWriter] Appended ${toAppend.length} new element(s) to: ${filePath}`);
  }

  private _groupByType(
    elements: DiscoveredElement[]
  ): Record<string, DiscoveredElement[]> {
    const groups: Record<string, DiscoveredElement[]> = {
      'Buttons': [],
      'Input Fields': [],
      'Dropdowns': [],
      'Navigation': [],
      'Other Elements': [],
    };

    elements.forEach((el) => {
      if (el.type === 'button') groups['Buttons'].push(el);
      else if (el.type === 'input' || el.type === 'textarea') groups['Input Fields'].push(el);
      else if (el.type === 'select') groups['Dropdowns'].push(el);
      else if (el.type === 'link') groups['Navigation'].push(el);
      else groups['Other Elements'].push(el);
    });

    return groups;
  }
}
