# Checkout Page Element Properties

# ─── Step One ─────────────────────────────────────────────────────────────────
FirstNameField=[data-test='firstName']
LastNameField=[data-test='lastName']
PostalCodeField=[data-test='postalCode']
ContinueButton=text=Continue
CancelButton=text=Cancel

# ─── Step Two ─────────────────────────────────────────────────────────────────
SummarySubtotal=.summary_subtotal_label
SummaryTax=.summary_tax_label
SummaryTotal=.summary_total_label
FinishButton=text=Finish
BackButton=text=Back to Products

# ─── Success ──────────────────────────────────────────────────────────────────
ConfirmationHeader=//h2[text()='Thank you for your order!']
ConfirmationMessage=.complete-text
BackHomeButton=text=Back Home
CheckmarkImage=.pony_express
