# TeleConnect - CRM Login Page

CRMButton=//button[@data-testid='quick-login-crm']
LoginSubmit=//button[@data-testid='login-submit']

# TeleConnect - CRM Review Pop-up
CRMHomePage=//h1[text()='CRM Dashboard']
CRMReview=(//button[@data-testid='btn-start-review'])[1]
CRMReviewNotes=//textarea[@data-slot='textarea']
CRMReviewButton=//button[@data-testid='btn-confirm-review']
CRMApproveButton=(//button[@data-testid='btn-approve'])[1]
CRMPopupCustomerID=//span[text()='Customer ID verified']
CRMPopupAddress=//span[text()='Address is serviceable']
CRMPopupPlanElig=//span[text()='Plan eligibility confirmed']
CRMPopupApproveOrder=//button[@data-testid='btn-confirm-approve']
#CRMButtonApprove=(//button[@data-testid='btn-approve'])[1]

CRMStatus=(//span[text()='CRM APPROVED'])[1]

# TeleConnect - CRM Logout
CRMLogout=//button[text()='Logout']