# TeleVerify - Customer Dashboard
DashboardHeading=//h1[@data-testid='welcome-heading']
OrderList=//h2[text()='Recent Orders']/parent::div/parent::div
OrderCard=(//div[contains(@data-testid,'order-card')])[1]
OrderStatusBadge=(//div[contains(@data-testid,'order-card')])[1]//span[@data-slot='badge']

# TeleVerify - Logout
BtnLogout=//button[normalize-space()='Logout']
