# TeleConnect - Login Page 
SigninEmail=//input[@data-testid='login-email']
#SigninPassword=//input[@data-testid='login-password']
SigninPassword=//input[@id='password']
SigninButton=//button[@data-testid='login-submit']

# TeleConnect - Home Page 
HomepageWelcomeNote=//h1[@data-testid='welcome-heading']
HomepageLogout=//button[text()='Logout']